import { PullRequest } from './github';

export interface DigestSection {
  title: string;
  prs: PullRequest[];
  summary: string;
}

export interface DigestOptions {
  repoName: string;
  startDate: Date;
  endDate: Date;
  sections: DigestSection[];
}

export function formatMarkdownDigest(options: DigestOptions): string {
  const { repoName, startDate, endDate, sections } = options;

  const dateRange = `${formatDate(startDate)} – ${formatDate(endDate)}`;

  const lines: string[] = [
    `# 📋 Weekly PR Digest: ${repoName}`,
    ``,
    `**Period:** ${dateRange}`,
    `**Total PRs merged:** ${sections.reduce((acc, s) => acc + s.prs.length, 0)}`,
    ``,
    `---`,
    ``,
  ];

  for (const section of sections) {
    if (section.prs.length === 0) continue;

    lines.push(`## ${section.title} (${section.prs.length})`);
    lines.push(``);
    lines.push(`> ${section.summary}`);
    lines.push(``);

    for (const pr of section.prs) {
      const author = pr.author ? `@${pr.author}` : 'unknown';
      lines.push(`- [#${pr.number} ${escapeMd(pr.title)}](${pr.url}) — ${author}`);
    }

    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by [pr-digest](https://github.com/marketplace/actions/pr-digest)*`);

  return lines.join('\n');
}

export function formatSlackDigest(options: DigestOptions): string {
  const { repoName, startDate, endDate, sections } = options;
  const dateRange = `${formatDate(startDate)} – ${formatDate(endDate)}`;
  const totalPRs = sections.reduce((acc, s) => acc + s.prs.length, 0);

  const blocks: string[] = [
    `*📋 Weekly PR Digest: ${repoName}*`,
    `_${dateRange} · ${totalPRs} PRs merged_`,
    ``,
  ];

  for (const section of sections) {
    if (section.prs.length === 0) continue;
    blocks.push(`*${section.title}* (${section.prs.length})`);
    blocks.push(section.summary);
    for (const pr of section.prs) {
      blocks.push(`  • <${pr.url}|#${pr.number}> ${pr.title}`);
    }
    blocks.push(``);
  }

  return blocks.join('\n');
}

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function escapeMd(text: string): string {
  return text.replace(/[\[\]]/g, '\\$&');
}
